Enable redrive policy in config file
p4tin/goaws pull request #192
Opened 2019-02-08 16:27 UTC by pswaminathan

Currently there is no support for putting a redrive policy in the config file, e.g.

```yaml
  Queues:
    - Name: failed-messages
    - Name: messages
      RedrivePolicy: '{"deadLetterTargetArn":"arn:aws:sqs:us-west-2:100010001000:failed-messages","maxReceiveCount":10}'
      VisibilityTimeout: 5
```

This adds support for it by pulling the redrive policy logic into a separate function and calling it when creating queues from the config.

2019-02-14 21:49 UTC, pswaminathan commented
Hi @p4tin — do you have any thoughts on this?

2021-05-15 13:25 UTC, p4tin commented
Your PR has errors in the build!

`package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)`

2021-05-15 13:26 UTC, p4tin requested changes
Fix build errors!

2021-05-15 13:51 UTC, p4tin commented
I have merged #235 which provides this capability.

2021-05-15 13:51 UTC, closed without merging

2021-05-17 16:45 UTC, pswaminathan commented
It is worth noting that:

1. This built and ran two years ago when I made the PR—I built off this branch and used at a previous company
2. The specific error implies an error in the Go environment (given that math/bits is in the standard library), rather than an issue with this code
3. math/bits wasn't even involved in this change
4. I hadn't rebased on master since I thought this was abandoned

I am glad the functionality is merged, in some form or fashion.